---
- name: Install New Relic
  hosts: gcp
  roles:
    - role: newrelic.newrelic_install
      vars:
        targets:
          - infrastructure
          - logs
          - nginx
        verbosity: debug
  environment:
    NEW_RELIC_API_KEY: <nr-api-key>
    NEW_RELIC_ACCOUNT_ID: <nr-account-id>
    NEW_RELIC_REGION: <region-ex:US/EU>
