---
- name: Install New Relic
  hosts: gcp
  roles:
    - role: newrelic.newrelic_install
      vars:
        targets:
          - infrastructure
          - logs
          - nginx
        verbosity: debug
  environment:
    NEW_RELIC_API_KEY: <nr-api-key>
    NEW_RELIC_ACCOUNT_ID: <nr-account-id>
    NEW_RELIC_REGION: <region-ex:US/EU>

- name: Fetch GKE Cluster Credentials
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Fetch GKE Cluster Credentials
      ansible.builtin.command: gcloud container clusters get-credentials <cluster-name> --zone us-central1-a --project <project-id>
      changed_when: false

- name: Create New Relic Namespace
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Namespace
          apiVersion: v1
          metadata:
            name: newrelic

- name: Deploy New Relic Bundle on GKE
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install New Relic Bundle
      kubernetes.core.helm:
        name: newrelic-bundle
        chart_ref: newrelic/nri-bundle
        release_namespace: newrelic
        values_files:
          - values-newrelic.yaml
        state: present
